### ISSUE TITLE
vue-cli中css modules开启后，引入的第三方库样式失效怎么解决？求大佬分析一波。

### ISSUE THREAD

**Issue by linbaichuan0818** [ZhengXiaowei/base-vue-tsx-template#1]
按网上的方法webpack中配置https://www.jianshu.com/p/603a61471ff6。还是无效。网上搜索了蛮多。也没有解决。求大佬帮忙分析一下。

**Comment by ZhengXiaowei** [comment]
vue.config.js里配置parallel为false后再试试。

**Comment by linbaichuan0818** [comment]
ERROR  Failed to compile with 2 errors                                                                                  10:59:02 PM
 error  in ./node_modules/ant-design-vue/es/button/style/index.css

Syntax Error: SyntaxError
Unknown word

> 1 | var api = require("!../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../../../../css-loader/dist/cjs.js??ref--18-1!./index.css");
目前是报这个错；
然后我用了你那个插件tsImportPluginFactory


const tsImportPluginFactory = require("ts-import-plugin");
module.exports = {
  parallel: false,
  css: {
    requireModuleExtension: false // 开启CSS module
  },
  configureWebpack: {
    resolve: {
      extensions: [".js", ".vue", ".json", ".ts", ".tsx"] // 加入ts 和 tsx
    },
    module: {
      rules: [

        {//ES6、JSX处理
          test: /(\.tsx|\.ts)$/,
          exclude: /node_modules/,
          loader: 'ts-loader',
          options:
          {
            transpileOnly: true,
            getCustomTransformers: () => ({
              before: [
                tsImportPluginFactory({
                  libraryName: "ant-design-vue",
                  libraryDirectory: "es",
                  style: "css"
                })
              ]
            }),
            compilerOptions: {
              module: "es2015"
            }
          }
        },

        {//CSS处理
          test: /\.css$/,
          loader: "style-loader!css-loader?modules",
          exclude: /node_modules/,
        },

        {//antd样式处理
          test: /\.css$/,
          exclude: /src/,
          use: [
            { loader: "style-loader", },
            {
              loader: "css-loader",
              options: {
                importLoaders: 1
              }
            }
          ]
        },
      ]
    }
  }
};

**Comment by linbaichuan0818** [comment]
搞明白谢谢了，是requireModuleExtension: true 
不能省略xx.module.css中的module，让webapck解析。不然第三方组件库的样式会失效。

**Comment by ZhengXiaowei** [comment]
> 搞明白谢谢了，是requireModuleExtension: true
> 不能省略xx.module.css中的module，让webapck解析。不然第三方组件库的样式会失效。

哦哦，我的锅，没看仔细，我以为你是打包后组件样式没生效的问题。
